spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/auth/realms/chat/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8081/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}