spring:
  kafka:
    template:
      user-changed-topic: user-changed-topic
      notification-topic: notification-topic
    consumer:
      user-changed-group-id: user-changed-group-id

  sleuth:
    sampler:
      probability: 1.0