spring:    
  kafka:
    bootstrap-servers: http://localhost:9092

  datasource:
    url: jdbc:mysql://localhost:3306/friend?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    
  zipkin:
    base-url: http://localhost:9411
  