spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  kafka:
    template:
      notification-topic: notification-topic
      user-changed-topic: user-changed-topic
    consumer:
      user-changed-group-id: user-changed-group-id-2

  datasource:
    username: friend
    password: friend
    driver-class: com.mysql.cj.jdbc.Driver

  sleuth:
    sampler:
      probability: 1.0