server:
  port: 0

spring:
  kafka:
    bootstrap-servers: http://kafka:9092
    template:
      notification-topic: notification-topic
      user-changed-topic: user-changed-topic
    consumer:
      user-changed-group-id: user-changed-group-id-2