spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB

  kafka:
    template:
      avatar-changed-topic: avatar-changed-topic

  sleuth:
    sampler:
      probability: 1.0

eureka:
  gateway-uri: http://localhost:8082

minio:
  access-key: minio
  secret-key: miniopwd
  bucket: public
