server:
  port: 0

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB

  kafka:
    bootstrap-servers: http://kafka:9092
    template:
      avatar-changed-topic: avatar-changed-topic

minio:
  endpoint: http://minio:9000
  access-key: minio
  secret-key: miniopwd
  bucket: public
