server:
  port: 0

spring:
  kafka:
    bootstrap-servers: http://kafka:9092
    template:
      notification-topic: notification-topic
    consumer:
      notification-group-id: notification-group-id
