spring:
  kafka:
    template:
      avatar-changed-topic: avatar-changed-topic
      user-changed-topic: user-changed-topic
    consumer:
      avatar-changed-group-id: avatar-changed-group-id

  sleuth:
    sampler:
      probability: 1.0
      
keycloak:
  master-realm: master
  realm: chat
  client-id: admin-cli
  username: admin
  password: admin
