server:
  port: 0

spring:
  application:
    name: friend-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/chat
          jwk-set-uri: http://localhost:8090/auth/realms/chat/protocol/openid-connect/certs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka

  instance:
    instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
