server:
  port: 8082

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8090/auth/realms/chat/protocol/openid-connect/token
            authorization-uri: http://localhost:8090/auth/realms/chat/protocol/openid-connect/auth
            user-info-uri: http://localhost:8090/auth/realms/chat/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8090/realms/chat/protocol/openid-connect/certs
            user-name-attribute: preferred_username

        registration:
          keycloak:
            provider: keycloak
            client-id: auth-service
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'

      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/auth/realms/chat/protocol/openid-connect/certs

  cloud:
    gateway:
      default-filters:
      - TokenRelay

      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**

      - id: image-service
        uri: lb://image-service
        predicates:
        - Path=/images/**

      - id: friend-service
        uri: lb://friend-service
        predicates:
        - Path=/friend**
        
      - id: chat-service
        uri: lb://chat-service
        predicates:
        - Path=/chat/**, /ws/**
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka
