server:
  port: 0

spring:
  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/auth/realms/chat/protocol/openid-connect/certs
    
  kafka:
    bootstrap-servers: http://kafka:9092
    template:
      avatar-changed-topic: avatar-changed-topic
      user-changed-topic: user-changed-topic
    consumer:
      avatar-changed-group-id: avatar-changed-group-id

keycloak:
  auth-server-url: http://auth-service:8080/auth
  master-realm: master
  realm: chat
  client-id: admin-cli
  username: admin
  password: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8081/eureka
      
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}