server:
  port: 0

minio:
  endpoint: http://minio:9000
  access-key: minio
  secret-key: miniopwd
  bucket: public

spring:
  application:
    name: image-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/auth/realms/chat/protocol/openid-connect/certs

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB

  kafka:
    bootstrap-servers: http://kafka:9092
    template:
      avatar-changed-topic: avatar-changed-topic

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8081/eureka
  
  gateway-uri: http://localhost:8082

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}