server:
  port: 0

spring:
  application:
    name: chat-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/auth/realms/chat/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: http://kafka:9092
    template:
      user-changed-topic: user-changed-topic
      notification-topic: notification-topic
    consumer:
      user-changed-group-id: user-changed-group-id

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8081/eureka
      
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
