global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8082']
  
  - job_name: 'user-service'
    metrics_path: '/api/user-service/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8082']

  - job_name: 'friend-service'
    metrics_path: '/api/friend-service/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8082']
  
  - job_name: 'image-service'
    metrics_path: '/api/image-service/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8082']
  
  - job_name: 'chat-service'
    metrics_path: '/api/chat-service/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8082']

  - job_name: 'notification-service'
    metrics_path: '/api/notification-service/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8082']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']